/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.equifax.fabric.uk.nonlimitedregister.bnumber;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BNumber extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BNumber\",\"namespace\":\"com.equifax.fabric.uk.nonlimitedregister.bnumber\",\"fields\":[{\"name\":\"value\",\"type\":[\"null\",\"string\"],\"dataClassification\":\"3\"}],\"default\":null}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public BNumber() {}

  /**
   * All-args constructor.
   */
  public BNumber(java.lang.CharSequence value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /** Creates a new BNumber RecordBuilder */
  public static com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder newBuilder() {
    return new com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder();
  }
  
  /** Creates a new BNumber RecordBuilder by copying an existing Builder */
  public static com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder newBuilder(com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder other) {
    return new com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder(other);
  }
  
  /** Creates a new BNumber RecordBuilder by copying an existing BNumber instance */
  public static com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder newBuilder(com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber other) {
    return new com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder(other);
  }
  
  /**
   * RecordBuilder for BNumber instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BNumber>
    implements org.apache.avro.data.RecordBuilder<BNumber> {

    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing BNumber instance */
    private Builder(com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber other) {
            super(com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'value' field */
    public java.lang.CharSequence getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'value' field */
    public com.equifax.fabric.uk.nonlimitedregister.bnumber.BNumber.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public BNumber build() {
      try {
        BNumber record = new BNumber();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
